---
ddns:
  storage:
     sqlite:
      db: /var/simple-ddns.db
  public-ip-api:
     ipify:
      check-period-mins: 1
      ipv4:
        endpoint: https://api.ipify.org
      ipv6:
        endpoint: https://api6.ipify.org
  dns-server:
    aws:
      - account: main
        credentials-file: "/usr/local/etc/simple-ddns/aws/credentials"
        zones: 
          - id: "111111111111111111111"
            records:
              - fqdn: vpn.home.com.
                type: A
              - fqdn: jenkins.home.com.
                type: A
          - id: "222222222222222222222"
            records:
              - fqdn: vpn6.home.com.
                type: AAAA
              - fqdn: jenkins6.home.com.
                type: AAAA
      - account: secondary
        credentials-file: "/usr/local/etc/simple-ddns/aws/credentials-seconday"
        zones: 
          - id: "111111111111111111111"
            records:
              - fqdn: secondary.vpn.home.com.
                type: A
              - fqdn: secondary.jenkins.home.com.
                type: A
          - id: "222222222222222222222"
            records:
              - fqdn: secondary6.vpn.home.com.
                type: AAAA
              - fqdn: seconday6.jenkins.home.com.
                type: AAAA
    digital-ocean:
      - account: main
        api-key: "API-KEY"
        records:
          - fqdn: vpn.jorgesanchez-e.dev.
            type: A
          - fqdn: jenkins.jorgesanchez-e.dev.
            api-key: "API-KEY-ACCOUNT-2"
            type: A